# Generated by Django 3.1.1 on 2020-10-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201004_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='followers',
            new_name='following',
        ),
    ]
