# Generated by Django 3.1.1 on 2020-10-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201004_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='following_user',
        ),
    ]
