# Generated by Django 3.1.1 on 2020-10-05 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201005_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user',
            new_name='followed_user',
        ),
    ]
